import {FPS} from './kit';

// Voiceover clips (public/vo/<voice>/NN.mp3, generated by scripts/voiceover.py)
// and the second each one starts at. Each line lands on its scene; a few start
// a beat early, as trailer narration does, so no two lines overlap.
export const VOICES = ['tia', 'arthur'] as const;
export type Voice = (typeof VOICES)[number];

export const CLIPS: [string, number][] = [
  ['01', 0.3], // agents read everything
  ['02', 5.35], // meet HushGate
  ['03', 9.5], // personal data too
  ['04', 14.9], // zero leaks
  ['05', 18.8], // one view
  ['06', 21.5], // hijacked agent stopped
  ['07', 28.4], // spend capped
  ['08', 34.9], // shadow AI blocked
  ['09', 39.4], // nine controls
  ['10', 44.2], // on record
  ['11', 49.7], // HushGate. Use AI. Keep your secrets.
];

export const clipFrame = (seconds: number) => Math.round(seconds * FPS);
